# Generated by Django 4.0.4 on 2022-04-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
